Revert "Don't use run-on-gcp command"
This reverts commit 3f929845dcc5a1bae9c0c97780112bb5da5f1e53.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -78,7 +78,7 @@ commands:
 
             # Run A up on remote box
             GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
-            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
+            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -t -t ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
               << parameters.command >>
               exit;
             EOF
@@ -166,63 +166,25 @@ jobs:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASS
     steps:
-      - run:
-          # command-name: Verify generated sdk types
-          # instance-name: test-sdk
+      - run-on-gcp:
+          command-name: Verify generated sdk types
+          instance-name: test-sdk
           command: |
-            # cleanup code setup before starting actual execution
-            cleanup() {
-              # Delete GCP box
-              gcloud compute instances delete $GCLOUD_VM_NAME --quiet
-
-              # Delete GCP firewall
-              gcloud compute firewall-rules delete $GCLOUD_VM_NAME --quiet
-            }
-            trap cleanup EXIT
-
-            # authenticate into gcloud
-            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT_EMAIL --key-file=-
-            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
-            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-
-            GCLOUD_VM_NAME=test-sdk-$(date +%s)
-            echo "GCLOUD_VM_NAME" $GCLOUD_VM_NAME
-
-            export PROTOCOL_DIR=/home/circleci/project
-            git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
-            pwd "$PROTOCOL_DIR"
-            ls -la "$PROTOCOL_DIR"
-            cd "$PROTOCOL_DIR/service-commands/"
-            npm install --unsafe-perm
-
-            # add IP to firewall
-            CIRCLECI_IP=$(curl https://checkip.amazonaws.com)
-            gcloud compute firewall-rules create $GCLOUD_VM_NAME --source-ranges "$CIRCLECI_IP" --action allow --rules all
-
-            # run A setup on remote dev box to clone protocol and install the prerequisites for A
-            # A setup ... || true is necessary because exit code returns 141 by default
-            yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME --fast --spot-instance || true
-
-            # Run A up on remote box
-            GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
-            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
-              sudo apt update
-              sudo apt install -y default-jre
-              cd /home/ubuntu/audius-protocol
-              git pull
-              git checkout $CIRCLE_BRANCH
-              A up -nc 0
-              cd libs
-              npm run gen:dev
-              cd libs/src/sdk/api/generated
-              # Check if there are any changes generated
-              if [ -z "$(git status . --porcelain)" ]; then 
-                # If so, fail the build and ask the dev to generated types locally and check in those changes
-                printf '%s\n' "Found diff between generated types and checked in types, please `npm run gen:dev` in libs" >&2
-                exit 1    
-              fi
-              exit;
-            EOF
+            sudo apt update
+            sudo apt install -y default-jre
+            cd /home/ubuntu/audius-protocol
+            git pull
+            git checkout $CIRCLE_BRANCH
+            A up -nc 0
+            cd libs
+            npm run gen:dev
+            cd libs/src/sdk/api/generated
+            # Check if there are any changes generated
+            if [ -z "$(git status . --porcelain)" ]; then 
+              # If so, fail the build and ask the dev to generated types locally and check in those changes
+              printf '%s\n' "Found diff between generated types and checked in types, please `npm run gen:dev` in libs" >&2
+              exit 1    
+            fi
 
   test-libs:
     docker:
