Check git status

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,9 +26,17 @@ commands:
       command:
         description: The command to run on the gcp instance
         type: string
+      post-gcp-command:
+        description: The command to run after exiting the gcp ssh session
+        type: string
+      name:
+        description: The name of the step to display
+        default: Spin up gcp instance and run command
+        type: string
     steps:
       - run:
-          name: Spin up gcp instance and run command
+          name: << parameters.name >>
+          # This has to be one large run block because CircleCI doesn't preserve state across run steps
           command: |
             # cleanup code setup before starting actual execution
             cleanup() {
@@ -67,7 +75,10 @@ commands:
             GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
             ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
               << parameters.command >>
+              exit;
             EOF
+
+          << parameters.post-gcp-command >>
 
 
 # global parameters
@@ -84,65 +95,26 @@ jobs:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASS
     steps:
-      # This has to be one large run block because CircleCI doesn't preserve state across run steps
-      - run:
+      - run-on-gcp:
           name: Bake GCP Dev Image
           command: |
-            # cleanup code setup before starting actual execution
-            cleanup() {
-              # Delete GCP box
-              gcloud compute instances delete $GCLOUD_VM_NAME --quiet
+            # fail on error
+            set -e;
 
-              # Delete GCP firewall
-              gcloud compute firewall-rules delete $GCLOUD_VM_NAME --quiet
+            # on error, run this function
+            exit_ssh() {
+              exit $?
             }
-            trap cleanup EXIT
+            trap exit_ssh EXIT
 
-            # authenticate into gcloud
-            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT_EMAIL --key-file=-
-            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
-            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-            GCLOUD_VM_NAME=audius-bake-nightly-$(date +%s)
-            BAKE_IMAGE_NAME=ci-image-bake-latest
-            echo "$GCLOUD_VM_NAME" $GCLOUD_VM_NAME
-
-            export PROTOCOL_DIR=/home/circleci/project
-            git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
-            pwd "$PROTOCOL_DIR"
-            ls -la "$PROTOCOL_DIR"
-            cd "$PROTOCOL_DIR/service-commands/"
-            npm install --unsafe-perm
-
-            # add IP to firewall
-            CIRCLECI_IP=$(curl https://checkip.amazonaws.com)
-            gcloud compute firewall-rules create $GCLOUD_VM_NAME --source-ranges "$CIRCLECI_IP" --action allow --rules all
-
-            # run A setup on remote dev box to clone protocol and install the prerequisites for A
-            # A setup ... || true is necessary because exit code returns 141 by default
-            yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME || true
-
-            # Run A up on remote box
-            GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
-            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
-              # fail on error
-              set -e;
-
-              # on error, run this function
-              exit_ssh() {
-                exit $?
-              }
-              trap exit_ssh EXIT
-
-              # commands to prime the VM for the bake
-              A run init-repos up;
-              A up;
-              A run monitoring up;
-              A down;
-              cd audius-protocol/;
-              git checkout -f;
-              exit;
-            EOF
-
+            # commands to prime the VM for the bake
+            A run init-repos up;
+            A up;
+            A run monitoring up;
+            A down;
+            cd audius-protocol/;
+            git checkout -f;
+          post-gcp-command: |
             # Stop GCP box, can't take an image from a running VM
             gcloud compute instances stop $GCLOUD_VM_NAME
 
@@ -168,57 +140,18 @@ jobs:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASS
     steps:
-      # This has to be one large run block because CircleCI doesn't preserve state across run steps
-      - run:
+      - run-on-gcp:
           name: Test mad-dog on GCP
           command: |
-            # cleanup code setup before starting actual execution
-            cleanup() {
-              # Delete GCP box
-              gcloud compute instances delete $GCLOUD_VM_NAME --quiet
-
-              # Delete GCP firewall
-              gcloud compute firewall-rules delete $GCLOUD_VM_NAME --quiet
-            }
-            trap cleanup EXIT
-
-            # authenticate into gcloud
-            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT_EMAIL --key-file=-
-            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
-            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-
-            GCLOUD_VM_NAME=mad-dog-test-$(date +%s)
-            echo "GCLOUD_VM_NAME" $GCLOUD_VM_NAME
-
-            export PROTOCOL_DIR=/home/circleci/project
-            git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
-            pwd "$PROTOCOL_DIR"
-            ls -la "$PROTOCOL_DIR"
-            cd "$PROTOCOL_DIR/service-commands/"
-            npm install --unsafe-perm
-
-            # add IP to firewall
-            CIRCLECI_IP=$(curl https://checkip.amazonaws.com)
-            gcloud compute firewall-rules create $GCLOUD_VM_NAME --source-ranges "$CIRCLECI_IP" --action allow --rules all
-
-            # run A setup on remote dev box to clone protocol and install the prerequisites for A
-            # A setup ... || true is necessary because exit code returns 141 by default
-            yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME --fast --spot-instance || true
-
-            # Run A up on remote box
-            GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
-            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
-              cd /home/ubuntu/audius-protocol;
-              git pull;
-              git checkout $CIRCLE_BRANCH;
-              cd ./service-commands;
-              npm i
-              cd ../mad-dog;
-              A run init-repos up;
-              A up;
-              npm run start << parameters.mad-dog-type >> verbose;
-              exit;
-            EOF
+            cd /home/ubuntu/audius-protocol;
+            git pull;
+            git checkout $CIRCLE_BRANCH;
+            cd ./service-commands;
+            npm i
+            cd ../mad-dog;
+            A run init-repos up;
+            A up;
+            npm run start << parameters.mad-dog-type >> verbose;
 
   test-sdk:
     docker:
@@ -228,10 +161,19 @@ jobs:
           password: $DOCKERHUB_PASS
     steps:
       - run-on-gcp-instance:
+          name: Verify generated sdk types
           command: |
-            A up
+            A up -nc 0
             cd libs
             npm run gen:dev
+            cd libs/src/sdk/api/generated
+
+            # Check if there are any changes generated
+            if [ -z "$(git status . --porcelain)" ]; then 
+              # If so, fail the build and ask the dev to generated types locally and check in those changes
+              printf '%s\n' "Found diff between generated types and checked in types, please `npm run gen:dev` in libs" >&2
+              exit 1    
+            fi
 
   test-libs:
     docker:
