Add run-on-gcp-instance command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,6 +5,7 @@
 version: 2.1
 orbs:
   coveralls: coveralls/coveralls@1.0.6
+
 commands:
   diff-if-necessary:
     parameters:
@@ -20,6 +21,54 @@ commands:
                   value: << pipeline.git.branch >>
           steps:
             - run: ./diff.sh << parameters.service >> || (echo "no diff" && circleci-agent step halt)
+  run-on-gcp-instance:
+    parameters:
+      command:
+        description: The command to run on the gcp instance
+        type: string
+    steps:
+      - run:
+          name: Spin up gcp instance and run command
+          command: |
+            # cleanup code setup before starting actual execution
+            cleanup() {
+              # Delete GCP box
+              gcloud compute instances delete $GCLOUD_VM_NAME --quiet
+
+              # Delete GCP firewall
+              gcloud compute firewall-rules delete $GCLOUD_VM_NAME --quiet
+            }
+            trap cleanup EXIT
+
+            # authenticate into gcloud
+            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT_EMAIL --key-file=-
+            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
+            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
+
+            GCLOUD_VM_NAME=mad-dog-test-$(date +%s)
+            echo "GCLOUD_VM_NAME" $GCLOUD_VM_NAME
+
+            export PROTOCOL_DIR=/home/circleci/project
+            git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
+            pwd "$PROTOCOL_DIR"
+            ls -la "$PROTOCOL_DIR"
+            cd "$PROTOCOL_DIR/service-commands/"
+            npm install --unsafe-perm
+
+            # add IP to firewall
+            CIRCLECI_IP=$(curl https://checkip.amazonaws.com)
+            gcloud compute firewall-rules create $GCLOUD_VM_NAME --source-ranges "$CIRCLECI_IP" --action allow --rules all
+
+            # run A setup on remote dev box to clone protocol and install the prerequisites for A
+            # A setup ... || true is necessary because exit code returns 141 by default
+            yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME --fast --spot-instance || true
+
+            # Run A up on remote box
+            GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
+            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
+              << parameters.command >>
+            EOF
+
 
 # global parameters
 parameters:
@@ -178,50 +227,11 @@ jobs:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASS
     steps:
-      # This has to be one large run block because CircleCI doesn't preserve state across run steps
-      - run:
-          name: Setup GCP instance
+      - run-on-gcp-instance:
           command: |
-            # cleanup code setup before starting actual execution
-            cleanup() {
-              # Delete GCP box
-              gcloud compute instances delete $GCLOUD_VM_NAME --quiet
-
-              # Delete GCP firewall
-              gcloud compute firewall-rules delete $GCLOUD_VM_NAME --quiet
-            }
-            trap cleanup EXIT
-
-            # authenticate into gcloud
-            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT_EMAIL --key-file=-
-            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
-            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-
-            GCLOUD_VM_NAME=mad-dog-test-$(date +%s)
-            echo "GCLOUD_VM_NAME" $GCLOUD_VM_NAME
-
-            export PROTOCOL_DIR=/home/circleci/project
-            git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
-            pwd "$PROTOCOL_DIR"
-            ls -la "$PROTOCOL_DIR"
-            cd "$PROTOCOL_DIR/service-commands/"
-            npm install --unsafe-perm
-
-            # add IP to firewall
-            CIRCLECI_IP=$(curl https://checkip.amazonaws.com)
-            gcloud compute firewall-rules create $GCLOUD_VM_NAME --source-ranges "$CIRCLECI_IP" --action allow --rules all
-
-            # run A setup on remote dev box to clone protocol and install the prerequisites for A
-            # A setup ... || true is necessary because exit code returns 141 by default
-            yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME --fast --spot-instance || true
-
-      - run:
-          name: Run sdk tests
-          command: |
-            # Run A up on remote box
-            GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
-            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
-            EOF
+            A up
+            cd libs
+            npm run gen:dev
 
   test-libs:
     docker:
