DEBUG BOX

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -39,40 +39,40 @@ jobs:
             BAKE_IMAGE_NAME=ci-image-bake-latest
             echo "$GCLOUD_VM_NAME" $GCLOUD_VM_NAME
 
-            export PROTOCOL_DIR=/home/circleci/project
-            git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
-            pwd "$PROTOCOL_DIR"
-            ls -la "$PROTOCOL_DIR"
-            cd "$PROTOCOL_DIR/service-commands/"
-            npm install --unsafe-perm
+            # export PROTOCOL_DIR=/home/circleci/project
+            # git clone --branch "$CIRCLE_BRANCH" https://github.com/AudiusProject/audius-protocol.git "$PROTOCOL_DIR"
+            # pwd "$PROTOCOL_DIR"
+            # ls -la "$PROTOCOL_DIR"
+            # cd "$PROTOCOL_DIR/service-commands/"
+            # npm install --unsafe-perm
 
-            # run A setup on remote dev box to clone protocol and install the prerequisites for A
-            # A setup ... || true is necessary because exit code returns 141 by default
-            yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME || true
+            # # run A setup on remote dev box to clone protocol and install the prerequisites for A
+            # # A setup ... || true is necessary because exit code returns 141 by default
+            # yes | $PROTOCOL_DIR/service-commands/scripts/A setup remote-dev $GCLOUD_VM_NAME || true
 
-            # Run A up on remote box
-            GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
-            ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
-              A run init-repos up;
-              A up;
-              A down;
-              exit $?;
-            EOF
+            # # Run A up on remote box
+            # GCLOUD_IP_ADDRESS=$(gcloud compute instances describe $GCLOUD_VM_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
+            # ssh -o "StrictHostKeyChecking no" -i ~/.ssh/google_compute_engine -tt ubuntu@$GCLOUD_IP_ADDRESS \<< EOF
+            #   A run init-repos up;
+            #   A up;
+            #   A down;
+            #   exit $?;
+            # EOF
 
-            # Stop GCP box, can't take an image from a running VM
-            gcloud compute instances stop $GCLOUD_VM_NAME
+            # # Stop GCP box, can't take an image from a running VM
+            # gcloud compute instances stop $GCLOUD_VM_NAME
 
-            # Delete image with the same name (if exists)
-            gcloud compute images delete $BAKE_IMAGE_NAME --quiet || true
+            # # Delete image with the same name (if exists)
+            # gcloud compute images delete $BAKE_IMAGE_NAME --quiet || true
 
-            # Create the new CI bake image
-            gcloud compute images create "$BAKE_IMAGE_NAME" \
-              --project="$GOOGLE_PROJECT_ID" \
-              --source-disk="$GCLOUD_VM_NAME" \
-              --source-disk-zone="$GOOGLE_COMPUTE_ZONE" \
-              --storage-location=us
+            # # Create the new CI bake image
+            # gcloud compute images create "$BAKE_IMAGE_NAME" \
+            #   --project="$GOOGLE_PROJECT_ID" \
+            #   --source-disk="$GCLOUD_VM_NAME" \
+            #   --source-disk-zone="$GOOGLE_COMPUTE_ZONE" \
+            #   --storage-location=us
 
-            # Delete GCP box
+            # # Delete GCP box
             # echo "gcloud compute instances delete $GCLOUD_VM_NAME --quiet"
   test-mad-dog-e2e:
     # https://circleci.com/docs/2.0/parallelism-faster-jobs/
