[PROTO-1356] Tear down containers following self-hosted test (#6397)

diff --git a/.circleci/src/jobs/test-audius-cmd.yml b/.circleci/src/jobs/test-audius-cmd.yml
--- a/.circleci/src/jobs/test-audius-cmd.yml
+++ b/.circleci/src/jobs/test-audius-cmd.yml
@@ -7,4 +7,17 @@ steps:
   - run:
       name: audius-cmd test
       no_output_timeout: 15m
-      command: . ~/.profile; audius-compose up --prod && audius-cmd test
+      command: |
+        . ~/.profile
+        if ! (audius-compose up --prod && audius-cmd test); then
+          echo
+          echo "TEST FAILURE"
+          echo "Performing cleanup"
+          echo
+          audius-compose down
+          false
+        fi
+  - run:
+      name: cleanup
+      no_output_timeout: 15m
+      command: . ~/.profile; audius-compose down
